<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ScnSocialAuthDoctrineMongoODM\Options\ModuleOptions'             => __DIR__ . '/src/ScnSocialAuthDoctrineMongoODM/Options/ModuleOptions.php',
    'ScnSocialAuthDoctrineMongoODM\Document\UserProvider'             => __DIR__ . '/src/ScnSocialAuthDoctrineMongoODM/Document/UserProvider.php',
    'ScnSocialAuthDoctrineMongoODM\Service\UserProviderMapperFactory' => __DIR__ . '/src/ScnSocialAuthDoctrineMongoODM/Service/UserProviderMapperFactory.php',
    'ScnSocialAuthDoctrineMongoODM\Service\ModuleOptionsFactory'      => __DIR__ . '/src/ScnSocialAuthDoctrineMongoODM/Service/ModuleOptionsFactory.php',
    'ScnSocialAuthDoctrineMongoODM\Module'                            => __DIR__ . '/src/ScnSocialAuthDoctrineMongoODM/Module.php',
    'ScnSocialAuthDoctrineMongoODM\Mapper\UserProvider'               => __DIR__ . '/src/ScnSocialAuthDoctrineMongoODM/Mapper/UserProvider.php',
);